# Generated by Django 5.2.10 on 2026-07-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_auto_20210624_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerotelefonico',
            name='costo_mensual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
